#version: '3.8'

volumes:
  cache_volume:

services:

  chatgpt_frontend:
    build:
      context: ./chatgpt-frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"  # Nginxで80番ポートをリッスンするため
    depends_on:
      - chatgpt_backend
    volumes:
      - ./chatgpt-frontend/output:/var/log/nginx
    environment:
      - TZ=Asia/Tokyo
    restart: always

  chatgpt_backend:
    build: ./chatgpt-backend
    ports:
      - "3100:3100"
    volumes:
      - ./chatgpt-backend/output:/app/output
    restart: always
    environment:
      - TZ=Asia/Tokyo
    env_file:
      - .env
