#version: '3.8'
volumes:
  cache_volume:

services:
  chatgpt_webapp:
    build: ./app
    ports:
      - "3100:3100"
    volumes:
      - ./app:/app
    restart: always
    environment:
      - TZ=Asia/Tokyo
    env_file:
      - .env

  redis:
    image: redis:latest
    volumes:
      - type: volume
        source: cache_volume
        target: /data
        volume:
          nocopy: true
    restart: always
    environment:
      - TZ=Asia/Tokyo

  log_writer:
    build: ./log_writer
    volumes:
      - ./log_writer:/app
    environment:
      - TZ=Asia/Tokyo
    depends_on:
      - redis
